require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TemperaturesController do

  # This should return the minimal set of attributes required to create a valid
  # Temperature. As you add validations to Temperature, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "degrees" => "1.5" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TemperaturesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all temperatures as @temperatures" do
      temperature = Temperature.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:temperatures)).to eq([temperature])
    end
  end

  describe "GET show" do
    it "assigns the requested temperature as @temperature" do
      temperature = Temperature.create! valid_attributes
      get :show, {:id => temperature.to_param}, valid_session
      expect(assigns(:temperature)).to eq(temperature)
    end
  end

  describe "GET new" do
    it "assigns a new temperature as @temperature" do
      get :new, {}, valid_session
      expect(assigns(:temperature)).to be_a_new(Temperature)
    end
  end

  describe "GET edit" do
    it "assigns the requested temperature as @temperature" do
      temperature = Temperature.create! valid_attributes
      get :edit, {:id => temperature.to_param}, valid_session
      expect(assigns(:temperature)).to eq(temperature)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Temperature" do
        expect {
          post :create, {:temperature => valid_attributes}, valid_session
        }.to change(Temperature, :count).by(1)
      end

      it "assigns a newly created temperature as @temperature" do
        post :create, {:temperature => valid_attributes}, valid_session
        expect(assigns(:temperature)).to be_a(Temperature)
        expect(assigns(:temperature)).to be_persisted
      end

      it "redirects to the created temperature" do
        post :create, {:temperature => valid_attributes}, valid_session
        expect(response).to redirect_to(Temperature.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved temperature as @temperature" do
        # Trigger the behavior that occurs when invalid params are submitted
        Temperature.any_instance.stub(:save).and_return(false)
        post :create, {:temperature => { "degrees" => "invalid value" }}, valid_session
        expect(assigns(:temperature)).to be_a_new(Temperature)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Temperature.any_instance.stub(:save).and_return(false)
        post :create, {:temperature => { "degrees" => "invalid value" }}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested temperature" do
        temperature = Temperature.create! valid_attributes
        # Assuming there are no other temperatures in the database, this
        # specifies that the Temperature created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(Temperature).to receive(:update).with({ "degrees" => "1.5" })
        put :update, {:id => temperature.to_param, :temperature => { "degrees" => "1.5" }}, valid_session
      end

      it "assigns the requested temperature as @temperature" do
        temperature = Temperature.create! valid_attributes
        put :update, {:id => temperature.to_param, :temperature => valid_attributes}, valid_session
        expect(assigns(:temperature)).to eq(temperature)
      end

      it "redirects to the temperature" do
        temperature = Temperature.create! valid_attributes
        put :update, {:id => temperature.to_param, :temperature => valid_attributes}, valid_session
        expect(response).to redirect_to(temperature)
      end
    end

    describe "with invalid params" do
      it "assigns the temperature as @temperature" do
        temperature = Temperature.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Temperature.any_instance.stub(:save).and_return(false)
        put :update, {:id => temperature.to_param, :temperature => { "degrees" => "invalid value" }}, valid_session
        expect(assigns(:temperature)).to eq(temperature)
      end

      it "re-renders the 'edit' template" do
        temperature = Temperature.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Temperature.any_instance.stub(:save).and_return(false)
        put :update, {:id => temperature.to_param, :temperature => { "degrees" => "invalid value" }}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested temperature" do
      temperature = Temperature.create! valid_attributes
      expect {
        delete :destroy, {:id => temperature.to_param}, valid_session
      }.to change(Temperature, :count).by(-1)
    end

    it "redirects to the temperatures list" do
      temperature = Temperature.create! valid_attributes
      delete :destroy, {:id => temperature.to_param}, valid_session
      expect(response).to redirect_to(temperatures_url)
    end
  end

end
